#!/bin/bash
# Based on http://openweathermap.org/current

API_KEY=5c34df2bf271eee9a9ff24fc13142f18

#TODO use geolocation data
# Check on http://openweathermap.org/find
CITY_ID=4459467


ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""

UNITS="imperial"

SYMBOL_CELSIUS="℃"
SYMBOL_FAHRENHEIT="℉"

WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=${UNITS}"

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
#echo $WEATHER_INFO
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[[:alpha:]]*\"' | awk -F ':' '{print $2}' | tr -d '"')
#echo $WEATHER_MAIN
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[[:digit:]]*' | awk -F ':' '{print $2}' | tr -d '"')
#echo $WEATHER_TEMP

#echo $WEATHER_INFO
#echo $WEATHER_MAIN
#echo $WEATHER_TEMP
#WEATHER_MAIN="Partly Cloudy"

if [[ "${UNITS}" = "imperial" ]]; then
    SYMBOL=${SYMBOL_FAHRENHEIT}
    URGENT_LOWER=32
    URGENT_HIGHER=100
else
    SYMBOL=${SYMBOL_CELSIUS}
    URGENT_LOWER=0
    URGENT_HIGHER=30
fi

if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
  #echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL}"
  echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL}"
  #echo ""
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
  #echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL}"
  echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL}"
  #echo ""
elif [[ "${WEATHER_MAIN}" = *Thunderstorm* ]]; then
  #echo "${ICON_STORM} ${WEATHER_TEMP}${SYMBOL}"
  echo "${ICON_STORM} ${WEATHER_TEMP}${SYMBOL}"
  #echo ""
elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
  #echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL}"
  echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL}"
  #echo "Partly Cloudy?"
  #echo ""
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
  #echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL}"
  echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL}"
  #echo ""
elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
  #echo "${ICON_FOG} ${WEATHER_TEMP}${SYMBOL}"
  echo "${ICON_FOG} ${WEATHER_TEMP}${SYMBOL}"
  #echo ""
else
  #echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL}"
  echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL}"
  #echo ""
fi

#if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
#  exit 33
#fi
